Add files via upload
US-EPA-CAMD/easey-db-scripts pull request #49
Opened 2024-08-28 20:36 UTC by ayang2017

modified views with union all and join table op_year

2024-09-10 16:21 UTC, mark-hayward-erg commented
@ayang2017 The query changes to the views look good.  I do have a few notes for things that need to be updated:

- The "DROP VIEW IF EXISTS..." statement needs to remain in each of the view SQL scripts (as the first statement before the "CREATE OR REPLACE VIEW..." statement)
- The view scripts also need to be added to the "deployments/campd/release-v1.5-fix/6337" directory. 
  - The deployment directory needs to contain all the scripts that need to be executed to implement the changes.
- The DDL for the new camddmw.op_year table needs to be added as scripts under the "camddmw" folder
  - A new camddmw/tables/op_year.sql file needs to be added that contains the "CREATE TABLE IF NOT EXISTS..." statement and the "COMMENT..." statements
  - A new camddmw/constraints-indexes/op_year.sql file needs to be added that contains the "CONSTRAINT..." statement
  - See the account_fact.sql files in the above directories for an example

2024-09-10 16:21 UTC, mark-hayward-erg requested changes
See notes on the main conversation.

2024-09-12 16:50 UTC, ayang2017 commented
@mark-hayward-erg Scripts are updated and files are loaded to the locations you mentioned.

2024-09-27 13:51 UTC, mark-hayward-erg approved these changes

2024-09-27 13:51 UTC, merged