Add files via upload
US-EPA-CAMD/easey-db-scripts pull request #50
Opened 2024-08-28 21:40 UTC by ayang2017

2024-09-10 17:19 UTC, djw4erg requested changes
All the comments about 'return next' are just questions, not a request for a change.  **The use of 'return next' might be correct** since 'return next' is new to me.

The comment on ay_**update_ecmps_status_for_em_evaluation.sql** is a request for change.

2024-09-10 17:19 UTC, djw4erg commented on camdecmpswks/functions/ay_update_ecmps_status_for_em_evaluation.sql
A large portion of the code for the 'EM Evaluation' process in the UPDATE_ECMPS_STATUS procedure from ECMPS 1.0 (SQL Server) is missing from this version.  I extracted the 'EM Evaluation' code and included it below.  This code only includes the CHECK_SESSION delete and the EMISSION_EVALUATION update.

```
SET @SUBMITTABLE = 'N'

SELECT @SUBMITTABLE = 'Y'	
    FROM EM_SUBMISSION_ACCESS
    WHERE MON_PLAN_ID = @V_ID_KEY_OR_LIST AND
          RPT_PERIOD_ID = @V_PERIOD_ID AND
          SUBMISSION_AVAILABILITY_CD IN ('GRANTED', 'REQUIRE');

-- delete old evaluation data from check logs
DELETE FROM CHECK_SESSION 
    WHERE PROCESS_CD = 'HOURLY' AND
        MON_PLAN_ID = @V_ID_KEY_OR_LIST AND
        RPT_PERIOD_ID = @V_PERIOD_ID AND
        CHK_SESSION_ID <> @V_OTHER_FIELD

UPDATE EMISSION_EVALUATION
    SET NEEDS_EVAL_FLG	= 'N',
        CHK_SESSION_ID	= @V_OTHER_FIELD	
    WHERE MON_PLAN_ID = @V_ID_KEY_OR_LIST AND
        RPT_PERIOD_ID = @V_PERIOD_ID

-- Recreate the View Emission grid data
EXEC Client_EM_Grid_Data @V_MON_PLAN_ID = @V_ID_KEY_OR_LIST, @V_RPT_PERIOD_ID = @V_PERIOD_ID, @V_RESULT = @V_RESULT OUTPUT, @V_ERROR_MSG = @V_ERROR_MSG OUTPUT;

--
-- Deleting Calculated data failed, bail (PJR)
--
IF @V_RESULT = 'F'
    RETURN;

-- Update Monitoring Plan Needs Evaluation, if needed
EXEC UES.UpdateMpNeedsEvalForEmEvalIfNeeded @vChkSessionId = @V_OTHER_FIELD, @vMonPlanId = @V_ID_KEY_OR_LIST, @vResult = @V_RESULT OUTPUT, @vErrorMsg = @V_ERROR_MSG OUTPUT;

IF @V_RESULT = 'F'
    RETURN;


IF @SUBMITTABLE = 'Y' 
BEGIN
    INSERT INTO @tmpEmissionsStatus SELECT DISTINCT E.MON_PLAN_ID, E.RPT_PERIOD_ID
        FROM EMISSION_EVALUATION E,
        EM_SUBMISSION_ACCESS ESA,
        MONITOR_PLAN_LOCATION M, 
        REPORTING_PERIOD R,
        (SELECT MON_LOC_ID, EE.MON_PLAN_ID, EE.RPT_PERIOD_ID,
                CALENDAR_YEAR, QUARTER 
            FROM EMISSION_EVALUATION EE
                INNER JOIN REPORTING_PERIOD RP ON EE.RPT_PERIOD_ID = RP.RPT_PERIOD_ID
                INNER JOIN MONITOR_PLAN_LOCATION MPL ON EE.MON_PLAN_ID = MPL.MON_PLAN_ID) T
            WHERE E.MON_PLAN_ID = M.MON_PLAN_ID AND 
                E.RPT_PERIOD_ID = R.RPT_PERIOD_ID AND
                E.MON_PLAN_ID = ESA.MON_PLAN_ID AND 
                E.RPT_PERIOD_ID = ESA.RPT_PERIOD_ID AND
                ESA.SUBMISSION_AVAILABILITY_CD IN ('GRANTED','REQUIRE') AND
                M.MON_LOC_ID = T.MON_LOC_ID AND
                (R.CALENDAR_YEAR > T.CALENDAR_YEAR OR 
                (R.CALENDAR_YEAR = T.CALENDAR_YEAR AND R.QUARTER > T.QUARTER)) AND
                T.MON_PLAN_ID = @V_ID_KEY_OR_LIST  AND
                T.RPT_PERIOD_ID = cast(@V_PERIOD_ID as varchar);


    DECLARE EM_CSR CURSOR local FOR
        SELECT MON_PLAN_ID, RPT_PERIOD_ID
        FROM @tmpEmissionsStatus;

    OPEN EM_CSR;
    FETCH EM_CSR INTO @V_MON_PLAN_ID, @V_RPT_PERIOD_ID;

    WHILE (@@fetch_status = 0) 
    BEGIN
        EXEC dbo.DEL_CALCULATED_EMISSIONS_DATA @V_MON_PLAN_ID = @V_MON_PLAN_ID, @V_RPT_PERIOD_ID = @V_RPT_PERIOD_ID, @V_RESULT = @V_RESULT OUTPUT, @V_ERROR_MSG = @V_ERROR_MSG OUTPUT;
        IF @V_RESULT = 'F'
            BREAK;
        FETCH EM_CSR INTO @V_MON_PLAN_ID, @V_RPT_PERIOD_ID;
    END

    CLOSE EM_CSR;
    DEALLOCATE EM_CSR;

    --
    -- Deleting Calculated data failed, bail (PJR)
    --
    IF @V_RESULT = 'F'
        RETURN;
END

```

2024-09-10 17:19 UTC, djw4erg commented on camdecmpswks/functions/ay_update_ecmps_status_for_mp_evaluation.sql
> +   return next;
Should this be a 'return' , not a 'return next'?

2024-09-10 17:19 UTC, djw4erg commented on camdecmpswks/functions/ay_update_ecmps_status_for_mp_evaluation.sql
> +   return next;
Should this be a 'return' , not a 'return next'?

2024-09-10 17:19 UTC, djw4erg commented on camdecmpswks/functions/ay_update_ecmps_status_for_em_evaluation.sql
> +   return next;
Should this be a 'return' , not a 'return next'?

2024-09-10 17:19 UTC, djw4erg commented on camdecmpswks/functions/ay_update_ecmps_status_for_em_evaluation.sql
> +  return next;
Should this be a 'return' , not a 'return next'?

2024-09-10 17:19 UTC, djw4erg commented on camdecmpswks/functions/ay_update_ecmps_status_for_qa_evaluation.sql
> +   return next;
Should this be a 'return' , not a 'return next'?

2024-09-10 17:19 UTC, djw4erg commented on camdecmpswks/functions/ay_update_ecmps_status_for_qa_evaluation.sql
> +   return next;
Should this be a 'return' , not a 'return next'?

2024-09-10 17:19 UTC, djw4erg commented on camdecmpswks/functions/ay_update_ecmps_status_for_qce_evaluation.sql
> +   return next;
Should this be a 'return' , not a 'return next'?

2024-09-10 17:19 UTC, djw4erg commented on camdecmpswks/functions/ay_update_ecmps_status_for_qce_evaluation.sql
> +   return next;
Should this be a 'return' , not a 'return next'?

2024-09-10 17:19 UTC, djw4erg commented on camdecmpswks/functions/ay_update_ecmps_status_for_tee_evaluation.sql
> +   return next;
Should this be a 'return' , not a 'return next'?

2024-09-10 17:19 UTC, djw4erg commented on camdecmpswks/functions/ay_update_ecmps_status_for_tee_evaluation.sql
> +   return next;
Should this be a 'return' , not a 'return next'?

2024-09-10 17:19 UTC, djw4erg commented on camdecmpswks/functions/delete_calculated_em_data_from_workspace.sql
> +	 return next;
Should this be a 'return' , not a 'return next'?

2024-09-10 17:19 UTC, djw4erg commented on camdecmpswks/functions/delete_calculated_em_data_from_workspace.sql
> +   return next;
Should this be a 'return' , not a 'return next'?

2024-09-10 17:19 UTC, djw4erg commented on camdecmpswks/functions/emissions_grid_remove_eval.sql
> + return next;
Should this be a 'return' , not a 'return next'?

2024-09-10 17:19 UTC, djw4erg commented on camdecmpswks/functions/emissions_grid_remove_eval.sql
> +   return next;
Should this be a 'return' , not a 'return next'?

2024-09-18 16:05 UTC, ayang2017 commented
There are two functions called by em_evaluation that need create/update:
Client_EM_Grid_Data;
UES.UpdateMpNeedsEvalForEmEvalIfNeeded.



From: djw4erg ***@***.***>
Sent: Tuesday, September 10, 2024 1:20 PM
To: US-EPA-CAMD/easey-db-scripts ***@***.***>
Cc: Anna Yang ***@***.***>; Author ***@***.***>
Subject: Re: [US-EPA-CAMD/easey-db-scripts] Add files via upload (PR #50)

CAUTION: Don't open links or attachments unless you recognize the sender and know they are safe.

@djw4erg requested changes on this pull request.

All the comments about 'return next' are just questions, not a request for a change. The use of 'return next' might be correct since 'return next' is new to me.

The comment on ay_update_ecmps_status_for_em_evaluation.sql is a request for change.

________________________________

On camdecmpswks/functions/ay_update_ecmps_status_for_em_evaluation.sql<https://github.com/US-EPA-CAMD/easey-db-scripts/pull/50#discussion_r1752112991>:

A large portion of the code for the 'EM Evaluation' process in the UPDATE_ECMPS_STATUS procedure from ECMPS 1.0 (SQL Server) is missing from this version. I extracted the 'EM Evaluation' code and included it below. This code only includes the CHECK_SESSION delete and the EMISSION_EVALUATION update.

SET @SUBMITTABLE = 'N'



SELECT @SUBMITTABLE = 'Y'

    FROM EM_SUBMISSION_ACCESS

    WHERE MON_PLAN_ID = @V_ID_KEY_OR_LIST AND

          RPT_PERIOD_ID = @V_PERIOD_ID AND

          SUBMISSION_AVAILABILITY_CD IN ('GRANTED', 'REQUIRE');



-- delete old evaluation data from check logs

DELETE FROM CHECK_SESSION

    WHERE PROCESS_CD = 'HOURLY' AND

        MON_PLAN_ID = @V_ID_KEY_OR_LIST AND

        RPT_PERIOD_ID = @V_PERIOD_ID AND

        CHK_SESSION_ID <> @V_OTHER_FIELD



UPDATE EMISSION_EVALUATION

    SET NEEDS_EVAL_FLG = 'N',

        CHK_SESSION_ID = @V_OTHER_FIELD

    WHERE MON_PLAN_ID = @V_ID_KEY_OR_LIST AND

        RPT_PERIOD_ID = @V_PERIOD_ID



-- Recreate the View Emission grid data

EXEC Client_EM_Grid_Data @V_MON_PLAN_ID = @V_ID_KEY_OR_LIST, @V_RPT_PERIOD_ID = @V_PERIOD_ID, @V_RESULT = @V_RESULT OUTPUT, @V_ERROR_MSG = @V_ERROR_MSG OUTPUT;



--

-- Deleting Calculated data failed, bail (PJR)

--

IF @V_RESULT = 'F'

    RETURN;



-- Update Monitoring Plan Needs Evaluation, if needed

EXEC UES.UpdateMpNeedsEvalForEmEvalIfNeeded @vChkSessionId = @V_OTHER_FIELD, @vMonPlanId = @V_ID_KEY_OR_LIST, @vResult = @V_RESULT OUTPUT, @vErrorMsg = @V_ERROR_MSG OUTPUT;



IF @V_RESULT = 'F'

    RETURN;





IF @SUBMITTABLE = 'Y'

BEGIN

    INSERT INTO @tmpEmissionsStatus SELECT DISTINCT E.MON_PLAN_ID, E.RPT_PERIOD_ID

        FROM EMISSION_EVALUATION E,

        EM_SUBMISSION_ACCESS ESA,

        MONITOR_PLAN_LOCATION M,

        REPORTING_PERIOD R,

        (SELECT MON_LOC_ID, EE.MON_PLAN_ID, EE.RPT_PERIOD_ID,

                CALENDAR_YEAR, QUARTER

            FROM EMISSION_EVALUATION EE

                INNER JOIN REPORTING_PERIOD RP ON EE.RPT_PERIOD_ID = RP.RPT_PERIOD_ID

                INNER JOIN MONITOR_PLAN_LOCATION MPL ON EE.MON_PLAN_ID = MPL.MON_PLAN_ID) T

            WHERE E.MON_PLAN_ID = M.MON_PLAN_ID AND

                E.RPT_PERIOD_ID = R.RPT_PERIOD_ID AND

                E.MON_PLAN_ID = ESA.MON_PLAN_ID AND

                E.RPT_PERIOD_ID = ESA.RPT_PERIOD_ID AND

                ESA.SUBMISSION_AVAILABILITY_CD IN ('GRANTED','REQUIRE') AND

                M.MON_LOC_ID = T.MON_LOC_ID AND

                (R.CALENDAR_YEAR > T.CALENDAR_YEAR OR

                (R.CALENDAR_YEAR = T.CALENDAR_YEAR AND R.QUARTER > T.QUARTER)) AND

                T.MON_PLAN_ID = @V_ID_KEY_OR_LIST  AND

                T.RPT_PERIOD_ID = ***@***.***_PERIOD_ID as varchar);





    DECLARE EM_CSR CURSOR local FOR

        SELECT MON_PLAN_ID, RPT_PERIOD_ID

        FROM @tmpEmissionsStatus;



    OPEN EM_CSR;

    FETCH EM_CSR INTO @V_MON_PLAN_ID, @V_RPT_PERIOD_ID;



    WHILE (@@fetch_status = 0)

    BEGIN

        EXEC dbo.DEL_CALCULATED_EMISSIONS_DATA @V_MON_PLAN_ID = @V_MON_PLAN_ID, @V_RPT_PERIOD_ID = @V_RPT_PERIOD_ID, @V_RESULT = @V_RESULT OUTPUT, @V_ERROR_MSG = @V_ERROR_MSG OUTPUT;

        IF @V_RESULT = 'F'

            BREAK;

        FETCH EM_CSR INTO @V_MON_PLAN_ID, @V_RPT_PERIOD_ID;

    END



    CLOSE EM_CSR;

    DEALLOCATE EM_CSR;



    --

    -- Deleting Calculated data failed, bail (PJR)

    --

    IF @V_RESULT = 'F'

        RETURN;

END



________________________________

In camdecmpswks/functions/ay_update_ecmps_status_for_mp_evaluation.sql<https://github.com/US-EPA-CAMD/easey-db-scripts/pull/50#discussion_r1752281853>:

> +

+

+                      OPEN EM_CSR;

+                              FETCH EM_CSR INTO V_MON_PLAN_ID, V_RPT_PERIOD_ID;

+                                WHILE (@@fetch_status = 0) loop

+                                 select * into result, error_msg

+                                   from camdecmpswks.delete_calculated_em_data_from_workspace(V_MON_PLAN_ID, V_RPT_PERIOD_ID);

+                                     IF result = 'F' then

+                                      return next;

+                                  end if;

+                               end loop;

+                              CLOSE EM_CSR;

+                              DEALLOCATE EM_CSR;

+

+  end if;  --vSubmittable = 'Y'

+   return next;

Should this be a 'return' , not a 'return next'?

________________________________

In camdecmpswks/functions/ay_update_ecmps_status_for_mp_evaluation.sql<https://github.com/US-EPA-CAMD/easey-db-scripts/pull/50#discussion_r1752282024>:

> +                                   IF result = 'F' then

+                                      return next;

+                                  end if;

+                               end loop;

+                              CLOSE EM_CSR;

+                              DEALLOCATE EM_CSR;

+

+  end if;  --vSubmittable = 'Y'

+   return next;

+

+exception when others then

+    get stacked diagnostics error_msg := message_text;

+    result = 'F';

+    error_msg :='From update_ecmps_status_for_mp_evaluation' ||' '|| error_msg;

+

+   return next;

Should this be a 'return' , not a 'return next'?

________________________________

In camdecmpswks/functions/ay_update_ecmps_status_for_em_evaluation.sql<https://github.com/US-EPA-CAMD/easey-db-scripts/pull/50#discussion_r1752285286>:

> +

+    UPDATE camdecmpswks.EMISSION_EVALUATION

+            SET NEEDS_EVAL_FLG    = 'N',

+                CHK_SESSION_ID    = vchk_session_id

+            WHERE MON_PLAN_ID = vmon_plan_id AND

+                RPT_PERIOD_ID = vperiod_id;

+

+

+  return next;

+

+exception when others then

+    get stacked diagnostics error_msg:= message_text;

+    result = 'F';

+     error_msg :='From update_ecmps_status_for_em_evaluation' ||' '|| error_msg;

+

+   return next;

Should this be a 'return' , not a 'return next'?

________________________________

In camdecmpswks/functions/ay_update_ecmps_status_for_em_evaluation.sql<https://github.com/US-EPA-CAMD/easey-db-scripts/pull/50#discussion_r1752285401>:

> +    result := 'T';

+

+       DELETE FROM camdecmpswks.CHECK_SESSION

+            WHERE PROCESS_CD = 'HOURLY' AND

+                MON_PLAN_ID = vmon_plan_id AND

+                RPT_PERIOD_ID = vperiod_id AND

+                CHK_SESSION_ID <> vchk_session_id;

+

+    UPDATE camdecmpswks.EMISSION_EVALUATION

+            SET NEEDS_EVAL_FLG    = 'N',

+                CHK_SESSION_ID    = vchk_session_id

+            WHERE MON_PLAN_ID = vmon_plan_id AND

+                RPT_PERIOD_ID = vperiod_id;

+

+

+  return next;

Should this be a 'return' , not a 'return next'?

________________________________

In camdecmpswks/functions/ay_update_ecmps_status_for_qa_evaluation.sql<https://github.com/US-EPA-CAMD/easey-db-scripts/pull/50#discussion_r1752301563>:

> +                                                  (select distinct test_sum_id from camdecmpswks.tmpTestsStatus);

+

+                      OPEN EM_CSR;

+    [...]

2024-10-22 21:21 UTC, merged

2024-10-22 21:22 UTC, ayang2017 commented
Updated scripts as requested.