Feature/#6233 #6342 unit program
US-EPA-CAMD/easey-db-scripts pull request #52
Opened 2024-09-06 16:04 UTC by yonatan-dp

Tickets 6233 and 6342: 1) functionality to add a Unit, Unit Program, and Reporting Frequency grids to the "Unit Information" section of the "Monitoring Plans" screen 2) functionality to edit the non Load Based Indicator field in the Unit Attributes grid

2024-09-09 15:54 UTC, djw4erg requested changes
Need the main version of all four Deployment scripts in the main camdecmps and camdecmpswks folders.

**Note that the Unit script should not include the initial population in the main script.**  It makes sense in the deployment script.

2024-09-09 15:54 UTC, djw4erg commented on deployments/ecmps/release-v2.0-fix/Sprint9/6183/camdaux/client-config.sql
Does this belong with #6233 or #6342?

2024-09-09 16:21 UTC, yonatan-dp commented on deployments/ecmps/release-v2.0-fix/Sprint9/6183/camdaux/client-config.sql
@djw4erg, 
- copied all four deployment scripts in the main camdecmps and camdecmpswks folders.
- removed the initial population in the Unit table script from the main script and left it only in the deployment script. Unit table creation moved to the main camdecmpswks folder.
- On client-config.sql, this is from a Sprint-9 ticket.  This has not been merged to develop yet because the CBS endpoint that this calls has not been finalized. You are the reviewer on that ticket too (6183).  Both commits are showing on this PR because 6233/6342 is built on top of 6183 but 6183 has not yet been merged to develop.

2024-09-09 19:11 UTC, djw4erg commented on deployments/ecmps/release-v2.0-fix/Sprint10/6233/camdecmpswks/unit.sql
There may be arguments against it, but I believe that camdecmpswks.UNIT should have the FAC_ID column, since FAC_ID is it's parent key.

2024-09-11 18:05 UTC, yonatan-dp commented on deployments/ecmps/release-v2.0-fix/Sprint10/6233/camdecmpswks/unit.sql
I implemented this based on the requirement for the unit table here: https://github.com/US-EPA-CAMD/easey-ui/issues/6342).  See the table specification for CAMDECMPSWKS.UNIT.  But, as far as the merits of adding fac_id, I will defer to your judgement.

2024-09-11 18:19 UTC, djw4erg approved these changes

2024-09-11 18:20 UTC, djw4erg commented on deployments/ecmps/release-v2.0-fix/Sprint10/6233/camdecmpswks/unit.sql
Let's go ahead with it as is.

2024-09-11 18:20 UTC, merged