Fix/#6080 submission email
US-EPA-CAMD/easey-db-scripts pull request #54
Opened 2024-09-17 14:07 UTC by yonatan-dp

Defects reported for issue 6080.

2024-09-18 00:45 UTC, djw4erg requested changes
Yonatan, everything looks good except that the "main folder" version of the scripts do not seem to exist in the repository.

The scripts for changed objects should exist under the folder in the repository root with the schema name.  The scripts to implement changes should exist in the deployment folder.  Usually the whole script for non-tables and new tables, and update scripts for changed tables.

2024-09-18 09:34 UTC, yonatan-dp commented
> Yonatan, everything looks good except that the "main folder" version of the scripts do not seem to exist in the repository.
> 
> The scripts for changed objects should exist under the folder in the repository root with the schema name. The scripts to implement changes should exist in the deployment folder. Usually the whole script for non-tables and new tables, and update scripts for changed tables.

Yes, of course. I have corrected per your comment.  Also, please review camdecmps.vw_monitor_location. There was one already under the camdecmps schema root folder and I updated it to match whats in camdecmpswks. There is a slight variation in the query between what was in camdecmps and camdecmpswks.

2024-09-18 21:53 UTC, djw4erg approved these changes

2024-09-18 22:44 UTC, djw4erg requested changes

2024-09-18 22:44 UTC, djw4erg commented on camdecmpswks/functions/get-qatest-feedback.sql
Sorry I missed this, but this script belongs in the CAMDECMPSWKS folder, not the CAMDECMPS folder.

2024-09-18 22:44 UTC, djw4erg commented on camdecmpswks/functions/get-qce-feedback.sql
Sorry I missed this, but this script belongs in the CAMDECMPSWKS folder, not the CAMDECMPS folder.

2024-09-18 22:44 UTC, djw4erg commented on camdecmpswks/functions/get-tee-feedback.sql
Sorry I missed this, but this script belongs in the CAMDECMPSWKS folder, not the CAMDECMPS folder.

2024-09-19 15:33 UTC, merged

2024-09-19 17:33 UTC, yonatan-dp commented on camdecmpswks/functions/get-qatest-feedback.sql
Hi Dwayne, the scripts are already in the CAMDECMPSWKS folder. Did you mean you want them in the CAMDECMPS folder?  I put them in the CAMDECMPSWKS folder because they are processing workspace (non official data).

2024-09-19 17:33 UTC, yonatan-dp commented on camdecmpswks/functions/get-qce-feedback.sql
Hi Dwayne, the scripts are already in the CAMDECMPSWKS folder. Did you mean you want them in the CAMDECMPS folder?  I put them in the CAMDECMPSWKS folder because they are processing workspace (non official data).

2024-09-19 17:34 UTC, yonatan-dp commented on camdecmpswks/functions/get-tee-feedback.sql
Hi Dwayne, the scripts are already in the CAMDECMPSWKS folder. Did you mean you want them in the CAMDECMPS folder?  I put them in the CAMDECMPSWKS folder because they are processing workspace (non official data).