fix/#6422 Update table 2 of QA feedback reports for no errors submissions
US-EPA-CAMD/easey-db-scripts pull request #74
Opened 2024-11-14 19:31 UTC by EvanSun220

### **Related Tickets:**

- [Ticket 6422](https://github.com/orgs/US-EPA-CAMD/projects/2/views/43?sliceBy%5Bvalue%5D=EvanSun220&pane=issue&itemId=82764721&issue=US-EPA-CAMD%7Ceasey-ui%7C6422)

### **Updates:**
-  Removed the restrictions of exclude no error records returned from camdecmpswks.get-qatest-feedback function.

2024-12-05 16:16 UTC, djw4erg submitted a review, later dismissed

2024-12-09 17:43 UTC, mark-hayward-erg requested changes

2024-12-09 17:43 UTC, mark-hayward-erg commented on deployments/ecmps/release-v2.0-fix/Sprint13/6422/camdecmpswks/get-qatest-feedback.sql
@EvanSun220 deployment scripts for functions should not include the "DROP" statement. "CREATE OR REPLACE" is sufficient, and does not have the side effect of dropping dependent objects (which would then need to get recreated separately).

The exception to this rule would be circumstances where the signature of a function is changing, in which case, the "DROP" statement should be included. In this circumstance, scripts to recreate dependent objects should also be included in the deployments folder.

2024-12-09 19:08 UTC, mark-hayward-erg approved these changes

2024-12-09 19:09 UTC, merged